# Site wide configuration

title: "cenalulu's Tech Blog"
description: "Collection of everythings I want to record down especially for tech"
logo: logo.jpg # 120x120 px default image used for Twitter summary card
teaser: teaser.jpg # 400x250 px default teaser image used in image archive grid
locale:
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
    input: GFM
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: 
  name: cenalulu(卢钧轶)
  email: cenalulu@gmail.com
  twitter: cenalulu
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: logo.jpg # 160x160 px image for author byline
disqus-shortname: cenalulu


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
